# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_app', '0002_auto_20161221_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_due',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
